# Generated by Django 4.1.1 on 2022-10-04 03:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_post_created_at_alter_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.date(2022, 10, 4)),
        ),
    ]
