# Generated by Django 4.1.1 on 2022-10-05 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_follow_alter_post_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='user_follows',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='user_main',
        ),
        migrations.AddField(
            model_name='follow',
            name='Loged_di',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AddField(
            model_name='follow',
            name='followed_di',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
