# Generated by Django 4.1.1 on 2022-10-05 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_follow_user_follows_remove_follow_user_main_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='Loged_di',
            new_name='Loged_id',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='followed_di',
            new_name='followed_id',
        ),
    ]
