# Generated by Django 4.1.1 on 2022-10-06 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_loged_id_follow_loged_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.date(2022, 10, 6)),
        ),
    ]
