# Generated by Django 4.1.1 on 2022-10-20 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default='<function uuid4 at 0x00000231FA676820>', primary_key=True, serialize=False),
        ),
    ]
